title: 'Hugo Site'
baseURL: 'https://example.org/'
languageCode: 'en-us'
theme: 'paper'

params:
  color: 'linen'
  avatar: 'githubusercontent.com/u/394065'
  name: 'Matt'
  bio: 'Pushing out sites like what!'


menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 10
      
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 20
      
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 40
      
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 50

taxonomies:
  category: "categories"
  tag: "tags"
  series: "series"
